// AUTO-GENERATED by scripts/generate-project-images.mjs
// Do not edit this file directly.

export const generatedProjectImages: Record<string, string[]> = {
  "apec-backoffice": [
    "/projects/apec-backoffice/01-list1.webp",
    "/projects/apec-backoffice/02-list2.webp",
    "/projects/apec-backoffice/03-modal.webp"
  ],
  "apec-monitoring": [
    "/projects/apec-monitoring/01-main.webp",
    "/projects/apec-monitoring/02-header.webp",
    "/projects/apec-monitoring/03-list.webp",
    "/projects/apec-monitoring/04-modal.webp"
  ],
  "location-backoffice": [
    "/projects/location-backoffice/01-list.webp",
    "/projects/location-backoffice/02-modal.webp",
    "/projects/location-backoffice/03-list2.webp"
  ],
  "portfolio-site": [
    "/projects/portfolio-site/01-main.webp",
    "/projects/portfolio-site/02-list.webp",
    "/projects/portfolio-site/03-modal.webp",
    "/projects/portfolio-site/04-darkmain.webp"
  ]
};
